name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gitops-test:${SHORT_SHA} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gitops-test:${SHORT_SHA}

      - name : Clone ops repo, update, and push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/Rajdiwate/ops.git .
          sed -i 's|image: rajd0311/gitops-test:.*|image: rajd0311/gitops-test:${SHORT_SHA}|' deployment.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update k8s-test image to ${SHORT_SHA}"
          git push https://${PAT}@github.com/Rajdiwate/ops.git main
